language: python
sudo: false
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9-dev'
install:
  - pip install -r requirements/requirements.txt
  - pip install -r requirements/tests.txt
script:
  - pytest
