language: python
sudo: false
python:
- '2.7'
env:
- python2.7
install:
- pip install -r requirements.txt
script:
- pytest
notifications:
  slack:
    secure: j1SZaLDp3OWWTQYxmfBGclMrNW1cf+sCXsUacmXwGzmG/1yelbs5UoWMDTmmLsV5CQGMR8g7swxxnO+Nfx0TPUrm2c0Ga4QFTdKSC+bY6N3y+jGpgueAOoDYGKsBj+e0KSkMVGOMGCmqpRX0eEUh5Q5easRHxxqHs4pX9iEA3J33bCTi78rC/l51BFJ4W7g2OYBtht8kqFr14Cpvvr1QSY1pZu3pg+D3GIcHWUjUPkfTgkK3zFqKKk4Thd3vo2e7okLKL4bVsDe7j6dZDzB7/ZZjjcQsQGouagoo+Q2dZNwrV65YXSyl/Ft7bz3vY3NSVrDZAdcvcjA2ZhaCpm2GBiHJu8JE/T3Ik+plC2n751IUIm5OHaPiEqBqIikbM6MB7Zf8hwLWoAi8C/3ZRpkLEyGFVi7+l3hx6WgLs1m9r80/r+CON+RrrxOgZgaY4iPg6KWSvwdYOM7q+PuLXFg7w+MiOohrefA2tbubupqPPqg4sN2a5ugiL01RxAR23NQWU11INmuBUDBp7imZVHOue6TsLBUroPn48Ba2ApxSLbJ9es11fcPNlq84ywGxdbNNpwiC+v8njN5ltyH6AEk24gO7P9Mn+Bzc0BMO8cUmRCEcWqYYRgSIyldRKscTkxIlxIPtAgCq4skDLR7FfLfFhXrpszZRS58VdmJE7lJh4yU=
